//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoctorOffice
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Turns
    {
        public int TurnKey { get; set; }
        [DisplayName("Número")]
        public int Number { get; set; }
        [DisplayName("Fecha")]
        public Nullable<System.DateTime> DateTime { get; set; }
        [DisplayName("ID Médico")]
        public int MedicKey { get; set; }
        [DisplayName("ID Paciente")]
        public int PatientKey { get; set; }

        public string GetPrintContent()
        {
            Medics m = new Medics();
            Patients p = new Patients();

            using (DoctorOfficeEntities db = new DoctorOfficeEntities())
            {
                m = db.Medics.Find(this.MedicKey);
                p = db.Patients.Find(this.PatientKey);    
            }
            
            string content = 
                "Paciente" + "\n" +
                "    Nombre: " + p.Name + "\n" +
                "    Apellido: " + p.Surname + "\n" +
                "\n" +
                "Turno" + "\n" +
                "    Número de orden: " + this.Number + "\n" +
                "    Fecha: " + this.DateTime + "\n" +
                "\n" +
                "Médico" + "\n" +
                "    Nombre: " + m.Name + "\n" +
                "    Apellido: " + m.Surname;

            return content;
        }
    }
}
